#pragma once

// Important includes, dont touch it
#include <Windows.h>
#include <Psapi.h>
#include <iostream>
#include <algorithm>
#include <functional>
#include <numeric>
#include <string>
#include <vector>
#include <time.h>
#include <random>
#include <sstream>
#include <fstream>
#include <iomanip>
#include <ctime>
#include <set>
#include <map>
#include <unordered_map>
#include <memory>
#include <thread>
#include <array>
#include <deque>
#include <intrin.h>
#include <atomic>
#include <mutex>
#include <typeinfo>
#include "Vector.h"
#include <format>
#include "dt_recv.h"
#include "VMatrix.h"
#include "Color.h"
#include <limits>
#include "Windowsx.h"
#include <cstdint>

#include "NetVarManager.h"
#include "Vars.h"
#include "Misc.h"
#include "Utils.h"
#include "Interfaces.h"
#include "Globals.h"